@baseUrl = http://localhost:8080
# Login via auth.http first, then paste the token below.
# The token must carry the ownerId claim matching the resource being managed.
@token = PASTE_JWT_HERE
@spotId = REPLACE_WITH_SPOT_ID
@sectionId = REPLACE_WITH_SECTION_ID

### Create spot
# @name createSpot
POST {{baseUrl}}/spots
Content-Type: application/json
X-Correlation-ID: spot-create-1

{
  "sectionId": "{{sectionId}}",
  "location": "A1"
}

### Get spot by id
# @name getSpot
GET {{baseUrl}}/spots/{{spotId}}
Accept: application/json

### List spots
# @name listSpots
GET {{baseUrl}}/spots?search=A&page=0&perPage=10&sort=createdAt&dir=asc
Accept: application/json

### Change spot location
# @name changeSpotLocation
PATCH {{baseUrl}}/spots/{{spotId}}/location
Authorization: Bearer {{token}}
Content-Type: application/json
X-Correlation-ID: spot-location-1

{
  "location": "B2"
}

### Publish spot
# @name publishSpot
POST {{baseUrl}}/spots/{{spotId}}/publish
Authorization: Bearer {{token}}
X-Correlation-ID: spot-publish-1

### Unpublish spot
# @name unpublishSpot
POST {{baseUrl}}/spots/{{spotId}}/unpublish
Authorization: Bearer {{token}}
X-Correlation-ID: spot-unpublish-1

### Delete spot
# @name deleteSpot
DELETE {{baseUrl}}/spots/{{spotId}}
Authorization: Bearer {{token}}

### Update spot (full update)
# @name updateSpot
PUT {{baseUrl}}/spots/{{spotId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "location": "B2"
}
